ul.System.Collections.Generic.List_Metadata={
	Name="List",
	Namespace="ul.System.Collections.Generic",
	Comments="",
	Modifier=0,
	TypeID=2,
	IsAbstract=false,
	IsGenericTypeDefinition=false,
	Parent="ul.System.Object"
}
