ul.System.Reflection.Metadata.Member_Metadata={
	Name="Member",
	Namespace="ul.System.Reflection.Metadata",
	Comments="",
	Modifier=0,
	TypeID=2,
	IsAbstract=false,
	IsGenericTypeDefinition=false,
	Parent="ul.System.Object"
}
