ul.System.Reflection.Metadata.Type_Metadata={
	Name="Type",
	Namespace="ul.System.Reflection.Metadata",
	Comments="",
	Modifier=0,
	TypeID=2,
	IsAbstract=false,
	IsGenericTypeDefinition=false,
	Parent="ul.System.Object"
}
